package inhagdsc.mamasteps.calendar.domain;

import inhagdsc.mamasteps.calendar.dto.ScheduleDto;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
@Table(name = "schedules")
public class ScheduleEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "schedule_id", nullable = false)
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "route_id", nullable = true)
    private Long routeId;

    @Column(name = "start-at")
    private LocalDateTime startAt;

    @Column(name = "target_time_seconds")
    private int targetTimeSeconds;

    @Column(name = "auto-generated")
    private boolean autoGenerated = false;

    @Column(name = "created_at", columnDefinition = "timestamp")
    private String createdAt;

    @Column(name = "updated_at", columnDefinition = "timestamp")
    private String updatedAt;

    public ScheduleDto toDto() {
        ScheduleDto dto = new ScheduleDto();
        dto.setId(this.getId());
        dto.setRouteId(this.getRouteId());
        dto.setDate(this.getStartAt());
        dto.setTargetTimeSeconds(this.getTargetTimeSeconds());
        dto.setCreatedAt(this.getCreatedAt());
        dto.setUpdatedAt(this.getUpdatedAt());
        return dto;
    }

    public void update(ScheduleEntity scheduleEntity) {
        this.routeId = scheduleEntity.getRouteId();
        this.startAt = scheduleEntity.getStartAt();
        this.updatedAt = scheduleEntity.getUpdatedAt();
    }
}