package inhagdsc.mamasteps.calendar.domain;

import inhagdsc.mamasteps.calendar.dto.ScheduleDto;
import inhagdsc.mamasteps.map.domain.RouteEntity;
import inhagdsc.mamasteps.user.entity.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.Optional;

@Entity
@Getter
@Setter
@Table(name = "schedules")
public class ScheduleEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "schedule_id", nullable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "route_id", nullable = true)
    private RouteEntity route;

    @Column(name = "start-at")
    private LocalDateTime startAt;

    @Column(name = "target_time_seconds")
    private int targetTimeSeconds;

    @Column(name = "auto-generated")
    private boolean autoGenerated = false;

    @Column(name = "created_at", columnDefinition = "timestamp")
    private String createdAt;

    @Column(name = "updated_at", columnDefinition = "timestamp")
    private String updatedAt;

    public ScheduleDto toDto() {
        ScheduleDto dto = new ScheduleDto();
        dto.setId(this.getId());
        Optional.ofNullable(this.getRoute())
                .map(RouteEntity::getId)
                .ifPresent(routeId -> {
                    dto.setRouteId(this.getRoute().getId());
                });
        dto.setDate(this.getStartAt());
        dto.setTargetTimeSeconds(this.getTargetTimeSeconds());
        dto.setCreatedAt(this.getCreatedAt());
        dto.setUpdatedAt(this.getUpdatedAt());
        return dto;
    }

    public void update(ScheduleEntity scheduleEntity) {
        this.route = scheduleEntity.getRoute();
        this.startAt = scheduleEntity.getStartAt();
        this.updatedAt = scheduleEntity.getUpdatedAt();
    }
}